version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed (e.g., API keys)
      # - NEXT_PUBLIC_API_URL=https://api.example.com
    volumes:
      # Optional: For development, mount the source code
      # - .:/app
      # - /app/node_modules
      - ./public:/app/public:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
# Optional: Add a network if other services (e.g., a backend API) are needed
# networks:
#   default:
#     name: my-app-network
